### ISSUE TITLE
Precompile seems missing in TableShowUtils

### ISSUE THREAD

**Issue by jmgnve** [davidanthoff/QueryOperators.jl#13]
I was unable to use Query.jl on Julia 0.6.3 until I added a __precompile__() to TableShowUtils. Should I use a specific version of Query for that particular Julia version? Thanks for any tips!

**Comment by davidanthoff** [comment]
That is just a bug, thanks for pointing this out. I don't really understand why I didn't run into this so far, but clearly it should just pre-compile. I just tagged a new release, now we just need to wait until it gets merged in METADATA: https://github.com/JuliaLang/METADATA.jl/pull/15185
